import Header from "@/components/Header";
import { NextPage } from "next";
import Head from "next/head";

export const Cart: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <h1>Carrinho</h1>{" "}
      </main>
    </>
  );
};

export default Cart;
